version: "3.8"
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      - MONGO_DATABASE="devmotivators"
    ports:
      - 27017:27017

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongo
    ports:
      - 8081:8081

  client:
    build: ./client
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8000:8000

  server:
    build: ./server
    volumes:
      - ./server:/usr/src/app
    ports:
      - 4000:4000
    depends_on:
      - mongo
